# Generated by Django 4.0.3 on 2022-09-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='destination',
            new_name='Route',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='name',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='phone',
        ),
        migrations.AddField(
            model_name='bus',
            name='Book_Now',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
